name: instax
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0

  #BLoC
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Custom Repository
  user_repository:
    path: packages/user_repository
  post_repository:
    path: packages/post_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
