name: post_repository
description: Dart package which manages the posts.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

  # Firebase
  cloud_firestore: ^6.0.0

  # Equatable for value comparison
  equatable: ^2.0.7

  # Custom Repository
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
